# Change these first
owner: hamcool
repo: upptime

sites:
  - name: Eclipse Aus
    url: https://eclipsetravel.com.au/
  - name: Eclipse NZ
    url: https://eclipsetravel.co.nz/
  - name: Eclipse US
    url: https://eclipsetravel.com/
  - name: Eclipse Aus - Africa
    url: https://eclipsetravel.com.au/africa

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  #cname: demo.upptime.js.org
  baseUrl: /upptime
  logoUrl: https://eclipsetravel.com.au/wp-content/uploads/2024/08/eclipse-travel-logo.svg
  name: Eclipse website monitor
  introTitle: "Eclipse website monitoring"
  introMessage: This is a status page which uses real-time data from a GitHub repository. No server required — just GitHub Actions, Issues, and Pages. 
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
